### ISSUE TITLE
passwords are truncated to 8 chars

### ISSUE THREAD

**Issue by vixns** [jedisct1/pure-ftpd#112]
We are using pureftpd 1.0.47 ans mysql for storing users.

You can login to any account using the 8 first chars of its password, any extra char is ignored.
At first we thought the guilty was the hashing method (AFAIK crypt() is limited to 8 chars by design), so we changed MYSQLCrypt to "password",  but we still have this issue.

**Comment by jedisct1** [comment]
What  system are you running this on?

`crypt()` is only limited to 8 characters on very old systems where the libc only supports DES.

Do not use the MySQL `PASSWORD()` function, it offers no security at all.

These methods are here for legacy systems but there is absolutely no justification for using them in 2019.

Use scrypt or argon2.

**Comment by vixns** [comment]
agreed about crypt() and password(), I plan to upgrade to argon2, see #113 
I'm using the official debian packages from debian stable or testing

Anyway, this is another issue, this one is about the ability to log into any account using only the first 8 password chars

**Comment by vixns** [comment]
After recompiling with libsodium and use argon2, this issue no longer appends. I will not dig further because crypt and password should be deprecated.

**Comment by jedisct1** [comment]
You can take it as an opportunity to upgrade to version 1.0.48 :)
