### ISSUE TITLE
hash passwords with argon2

### ISSUE THREAD

**Issue by vixns** [jedisct1/pure-ftpd#113]
Using `echo -n "test" | argon2 fskfjqshjdf -e` to hash the passwords does not seems to work.
How can we generate   argon2 hashes  suitable for the Password field from the command line ?

**Comment by jedisct1** [comment]
What authentication backend are you using?

**Comment by vixns** [comment]
mysql

**Comment by jedisct1** [comment]
Obviously you're not going to use hash passwords beyond local testing, but its output should be compatible. You can use `-id` to create Argon2id hashes instead of the default Argon2i.

In the `pureftpd-mysql.conf` file, set `MYSQLCrypt` to `argon2`.

Pure-FTPd has to be compiled with libsodium.

**Comment by vixns** [comment]
Official debian packages are NOT compiled with libsodium.
Fixed after installing libsodium-dev package and recompiling.

**Comment by vixns** [comment]
Bug report sent to the debian maintainer.

**Comment by racke** [comment]
Uploaded fixed packages to Debian experimental.
