### ISSUE TITLE
building with rfc2640 no longer works with 1.0.48

### ISSUE THREAD

**Issue by odoucet** [jedisct1/pure-ftpd#114]
RFC 2640 is no longer working on 1.0.48. It is as the compile flag is ignored.

`./configure --with-rfc2640` on 1.0.47 : 
```
$ ./src/pure-ftpd --fscharset=utf8 --help |grep charset
-8      --fscharset     <opt>
-9      --clientcharset <opt>
```

`./configure --with-rfc2640` on 1.0.48 : 
```
$ ./src/pure-ftpd --fscharset=utf8 --help
./src/pure-ftpd: unrecognized option '--fscharset=utf8'
421 Unknown run-time option
```

Built on CentOS 7.6 with gcc 4.8.5

**Comment by jedisct1** [comment]
Yes, this option does not exist any more.

It now always assumes that the client and the filesystem use UTF8. You don't need `--fscharset=utf8`.

Support for other character sets never worked reliably, so that has been removed.
