### ISSUE TITLE
segfault in extauth

### ISSUE THREAD

**Issue by hudecof** [jedisct1/pure-ftpd#115]
Hi,

when using extauth got segfault

  - version: git/master, pure-ftpd v1.0.48 [privsep]
  - os: CentOS 7
  - compile options: `./configure --with-puredb --with-extauth --with-everything`
  - run command: `/srv/devel/pure-ftpd/src/pure-ftpd --bind 21 -p 30000:31000 -A -H  -d  -C 1 -lextauth:/var/run/ftpd.sock`

This setup is working with the CentOS7 repository package

  - pure-ftpd v1.0.47 [privsep]
  - pure-ftpd-1.0.47-2.el7.x86_64

Log message is
```
Apr  3 06:00:54 ftp01 kernel: pure-ftpd[5262]: segfault at ffffffff00000000 ip 00007f6a96183ef9 sp 00007ffd1769ae50 error 5 in libc-2.17.so[7f6a96137000+1c2000]
```

Not using `pure-authd`, but custom server to avoid forking.

**Comment by hudecof** [comment]
I tried to compile the `1.0.47` the same way. The extauth is working

**Comment by hudecof** [comment]
I tried to compile the 1.0.47 the same way.  I got segfault

**Comment by hudecof** [comment]
compiling git master with `--with-debug` do not segfault

**Comment by jedisct1** [comment]
Good catch, thanks!

A new version will be released shortly in order to address this.

**Comment by hudecof** [comment]
@jedisct1 the segfault is hard to miss in logs when debugging non working auth ;)
