### ISSUE TITLE
Unable to fetch info about user

### ISSUE THREAD

**Issue by DTbelieveIT** [jedisct1/pure-ftpd#123]
Hello,I meet a warning as follows when I exec ```pure-pw list ``` or ```pure-pw show XXX```. 
```
Warning: invalid line [user001]
Warning: invalid line [user002]
Unable to fetch info about user [user002] in file [/etc/pure-ftpd/pureftpd.passwd]
```
But actually I create user001 and user002 successfully. I can also cat the file ```pureftpd.passwd``` to view the two users.
```
user001:$6$SK.Ta6g/tA7UkZ/0$/Uu6oOgm7ikDLQxGAEW7cIJ2frwfbZOsotqGWfKILrORFEaFsqKErDw6IbV29uNmxPNBhk3Qftl4oxtfKcRJX/:1002:1002::./data/./::::::::::::
user002:$6$7vkI8Wqgakz6hIe0$BvSvAvmBzLo2OBRe3NLOHlZ0bmO3ZQKPZrh.Nzx7mfnQqSK0.rD.VGNZS2jjLWM/bjyONVh9Do91MnHpi6gjr1:1002:1002::./data/./::::::::::::
```

I don't know what 's the matter.My environment is```Debian GNU/Linux 9.8 (stretch)``` and I am looking forward to your answer. Thank you very much : )

**Comment by jedisct1** [comment]
How did you create the `pureftpd.passwd` file? 

If you didn't use `pure-pw` to do it, maybe the number of fields is not correct, or end of lines are Windows-style?

**Comment by DTbelieveIT** [comment]
@jedisct1 Thank you for your reply! Yeah , there may be some error in my ```pureftpd.passwd```.
The pure-ftpd is installed by apt, so I remove it with the ```--purge``` flag and reinstall it.
I use ```pure-pw``` to create user again and it is ok now.
```
# pure-pw list
user001             XXX                    
user002             XXX
```

Thank you very much : )
