### ISSUE TITLE
Deprecated OpenSSL EC supported curve functions

### ISSUE THREAD

**Issue by graxlop** [jedisct1/pure-ftpd#125]
Hello,

There are a number of deprecated OpenSSL functions being used in the pure-ftpd TLS code. For example, the code for selecting the TLS curve is using deprecated functions to hardcode the P-256 curve and can't specify multiple curves like some [newer OpenSSL functions](https://www.openssl.org/docs/man1.1.1/man3/SSL_CTX_set1_curves_list.html) would allow.

**Comment by jedisct1** [comment]
If this is causing an actual problem, a pull request would be welcome, as you obviously know about OpenSSL way better than I do.

If this isn't causing any problem, I'd rather not touch that code, as people are still installing pure-ftpd on systems with really old software.
