### ISSUE TITLE
RNFR fails when file have a backslash

### ISSUE THREAD

**Issue by rentalhost** [jedisct1/pure-ftpd#127]
**Version:** 1.0.47
**Server:** CentOS 6.10

Okay, I know that a file should not have a backslash on it. But for some reason, my system have some files like that (and I will fix that soon). The question here is that the `RNFR` command could not accept this file to be renamed to another name.

```ftp
Command:	RNFR strange\things.bin
Response:	553 Prohibited file name: strange\things.bin
```

So I am unable to rename it when server is Pure-FTPd, but I could do it directly via terminal:

```
mv strange\things.xlsx now-its-fine.bin
```

I tried change the FTP server to ProFTPD to check if it works on it, but I could not make the server works. So I have no clue about that. 

---

There are two versions ahead of that, but none fixes this issue (considering the [changelog](https://www.pureftpd.org/project/pure-ftpd/news/)), and I could not update it directly because I depends of WHM team (maybe I could, I don't know).

**Comment by jedisct1** [comment]
Backslashes can be interpreted in different ways. It can be used to escape the next character. It can be a directory separator. It can be part of a file name, but then get refused by some filesystems.

This is not a bug. As the response hints, this behavior is intentional.

**Comment by rentalhost** [comment]
@jedisct1 On CentOS 6.10, at least, it is not just one-backslash, but a double-backslash. So maybe it should fits to the _"It can be used to escape the next character"_ part. Anyway, I could list this file when I call `MLSD`. So if it is not allowed, maybe it should be ignored?

![image](https://user-images.githubusercontent.com/421851/58202765-c7d09480-7cae-11e9-8876-61b760131a0b.png)

**Comment by jedisct1** [comment]
This is how your shell displays it, not the actual file name. See how backslashes can be confusing? :)

**Comment by rentalhost** [comment]
@jedisct1 maybe it could checks if the file exists, and so accept the name to be rename from even with backslash?
