### ISSUE TITLE
Hide .ftpquota

### ISSUE THREAD

**Issue by sooslaca** [jedisct1/pure-ftpd#128]
Hi,

Would it be possible to hide .ftpquota? access to the file denied anyway so it should not make any difference.

I made the following patch for myself, but it looks work for some clients but on some I still see .ftpquota.

Thanks

```
--- src/ls.c.orig       2019-04-02 14:00:40.000000000 +0000
+++ src/ls.c    2019-06-05 15:17:13.888471883 +0000
@@ -680,7 +680,9 @@
                 (FI_NAME(s)[1] == '.' && FI_NAME(s)[2] == 0)) {
                 listfile(s, NULL);
             } else {
-                d = listfile(s, NULL);
+                if (strstr(FI_NAME(s), ".ftpquota") == NULL) {
+                    d = listfile(s, NULL);
+                }
             }
         }
         if (!d) {

```

**Comment by jedisct1** [comment]
As you said, access to the file is denied, so why lie to users?

In addition, there is nothing wrong with a path containing `.ftpquota` if virtual quotas are not used, but your diff would hide these unconditionally.
