### ISSUE TITLE
Add --version CLI flag

### ISSUE THREAD

**Issue by frlan** [jedisct1/pure-ftpd#134]
It would be nice to have a --version CLI option to show version and maybe some of the configuration/build time options.

**Comment by jedisct1** [comment]
It's displayed when you connect to it :)

**Comment by frlan** [comment]
This wasn't the idea behind the FR.  I'd like to have a call like 

$ pure-ftpd  --version

That could be used e.g. in shell scripts on servier side.

**Comment by BlueNoob** [comment]
> This wasn't the idea behind the FR. I'd like to have a call like
> 
> $ pure-ftpd --version
> 
> That could be used e.g. in shell scripts on servier side.

+1
