### ISSUE TITLE
How to check compilation flags of the server?

### ISSUE THREAD

**Issue by Amenel** [jedisct1/pure-ftpd#137]
Sorry if this has already been asked, but I've searched the Web to no avail.

I am setting up a CentOS 7 server and due to configure complaining about the absence of libmysqlclient when it shouldn't have been. Tired of trying to sort that out, I have resorted to installing the Pure-FTPd package from the official repos.

The documentation says this about TLS and `--with-tls`:

    # Do _not_ uncomment this blindly. Double check that:
    # 1) The server has been compiled with TLS support (--with-tls),

My question is: how can I check that the server that is in the package I'm installing has been compiled with that flag?

From my understanding of the "do not uncomment blindly" sentence, something bad may happen if I start the server in TLS without first performing the checks.

My trying to compile from source was to be sure that the flag is used in the compilation.

**Comment by jedisct1** [comment]
If support for TLS hasn't been compiled in, the server will not start, complaining about a syntax error since it doesn't know about TLS-related options.

So, just try and if this is what happens, TLS support is not present.
