### ISSUE TITLE
Feature request: option hidedotfiles

### ISSUE THREAD

**Issue by areqq** [jedisct1/pure-ftpd#139]
Option opposite to  "displaydotfiles"

**Comment by jedisct1** [comment]
Hi!

This is usually something you can configure on the client.

Take a look at the preferences or config file, there's probably some setting for that :)

**Comment by areqq** [comment]
I want to hide dotfiles from users forbid them to see them at all.

**Comment by jedisct1** [comment]
Don't lie to your users :) They can find out what files are there no matter what.
