### ISSUE TITLE
Ubuntu pure-ftpd-ldap package cannot validate forced UIDs and GIDs

### ISSUE THREAD

**Issue by jamieshaw** [jedisct1/pure-ftpd#141]
When following these [instructions](https://help.ubuntu.com/community/PureFTP), but downloading the `pure-ftpd-ldap` package opposed to the standard one, if a user includes either configuration following parameters to the LDAP config file, it fails to validate; despite both corresponding GID and UID properties being set.
`LDAPForceDefaultUID`
`LDAPForceDefaultGID`

Is this a known bug? A feature by design?

Ideally, I believe this is the solution I am looking for just to authenticate LDAP users against a remote server but grant permission to a single directory on the host server (opposed to the homeDirectory of the LDAP user). However, due to configuration _'errors'_, I cannot proceed.

Any help would be appreciated.

**Comment by jedisct1** [comment]
Maybe your configuration file includes `MinUID` to explicitly deny connection from users with an uid below some value, and what you are trying to use with `LDAPForceDefaultUID` is. below that value?

**Comment by jamieshaw** [comment]
It did, and was, but I've commented that line out now.
It was previously set to 500, UID is set to 1002, GID is 1003.

Same error, exit 252.

**Comment by jedisct1** [comment]
Maybe the user directory is not accessible from that UID?

**Comment by jamieshaw** [comment]
Think I've answered my own question; digging through the source files, it looks as though the `pure-ftpd-package` is/was built with an older `log_ldap.c` file that doesn't include these options.

Time to manually build from source.

Thanks for the help.

**Comment by jedisct1** [comment]
Wow. These options were added in 2013.

**Comment by jamieshaw** [comment]
_Yeaaahhh_, seems like it's way into the Ubuntu 16.04 package before they moved onto the newer builds – last build was at 1.0.36.
