### ISSUE TITLE
rhost empty with tls failed logins

### ISSUE THREAD

**Issue by jjxtra** [jedisct1/pure-ftpd#143]
When using explicit TLS, the rhost in the auth.log file is empty. Why is that? Is it a bug or a configuration issue?

**Comment by jedisct1** [comment]
Can you clarify what `rhost` is?

`pure-ftpd` logs as the `ftp` facility, not `auth`.

**Comment by jjxtra** [comment]
Seeing this in /var/log/auth.log:

```
Aug 15 21:57:54 server_name pure-ftpd: pam_unix(pure-ftpd:auth): authentication failure; logname= uid=0 euid=0 tty=pure-ftpd ruser=user_name rhost=
```

**Comment by jedisct1** [comment]
Ah, this is a PAM thing.

bd729f82ad08aaf6b398b344352a7edc9ef574be may fix it (untested, I don't use Linux).
