### ISSUE TITLE
Perfect Forward Secrecy support?

### ISSUE THREAD

**Issue by ekodo** [jedisct1/pure-ftpd#19]
Is it currently possible to use ECDHE ciphers with pureftpd?

For example:

```ECDHE-RSA-AES256-GCM-SHA384 TLSv1.2 Kx=ECDH     Au=RSA  Enc=AESGCM(256) Mac=AEAD```

**Comment by jedisct1** [comment]
This has finally been implemented :)

**Comment by ekodo** [comment]
thank you! :)
