### ISSUE TITLE
Is there a command to check which release of pure-ftpd is installed on OSX?

### ISSUE THREAD

**Issue by diyaraniwar** [jedisct1/pure-ftpd#23]

**Comment by jedisct1** [comment]
`pure-ftpd --help` displays the version.

**Comment by diyaraniwar** [comment]
This is all I get from "pure-ftpd --help"

$ pure-ftpd --help
-0	--notruncate	
-1	--logpid	
-4	--ipv4only	
-6	--ipv6only	
-A	--chrooteveryone	
-a	--trustedgid	<opt>
-b	--brokenclientscompatibility	
-B	--daemonize	
-C	--maxclientsperip	<opt>
-c	--maxclientsnumber	<opt>
-d	--verboselog	
-D	--displaydotfiles	
-e	--anonymousonly	
-E	--noanonymous	
-f	--syslogfacility	<opt>
-F	--fortunesfile	<opt>
-g	--pidfile	<opt>
-G	--norename	
-h	--help	
-H	--dontresolve	
-I	--maxidletime	<opt>
-i	--anonymouscantupload	
-j	--createhomedir	
-K	--keepallfiles	
-k	--maxdiskusagepct	<opt>
-l	--login	<opt>
-L	--limitrecursion	<opt>
-M	--anonymouscancreatedirs	
-m	--maxload	<opt>
-N	--natmode	
-n	--quota	<opt>
-o	--uploadscript	
-O	--altlog	<opt>
-p	--passiveportrange	<opt>
-P	--forcepassiveip	<opt>
-q	--anonymousratio	<opt>
-Q	--userratio	<opt>
-r	--autorename	
-R	--nochmod	
-s	--antiwarez	
-S	--bind	<opt>
-t	--anonymousbandwidth	<opt>
-T	--userbandwidth	<opt>
-U	--umask	<opt>
-u	--minuid	<opt>
-V	--trustedip	<opt>
-w	--allowuserfxp	
-W	--allowanonymousfxp	
-x	--prohibitdotfileswrite	
-X	--prohibitdotfilesread	
-y	--peruserlimits	<opt>
-z	--allowdotfiles	
-Z	--customerproof

**Comment by jedisct1** [comment]
Try as root (prefix with `sudo`).

**Comment by diyaraniwar** [comment]
Thank you!
