### ISSUE TITLE
Custom TLS cert folder

### ISSUE THREAD

**Issue by Ninos** [jedisct1/pure-ftpd#25]
Hey there,
I'm on the way to implement pureftpd-mysql into an open source isp called i-mscp (http://i-mscp.net). Atm all's working fine, I just found out, that I need to copy my cert to following path: `/etc/ssl/private/pure-ftpd.pem`
Is it also possible to define a custom path? Otherwise after every update/installation I need to copy the cert to following folder. Atm it's placed at `/etc/imscp/imscp_services.pem` and it's also used by imap/pop3/smtp-servers...

Would be nice to have a solution for that.

Best regards,
Ninos

PS: How's the performance on a system with many ftp-users?
PS²: Is there anywhere a documentation for all possible sql-placeholders?

**Comment by Burnett01** [comment]
Hey I'm not quite sure if a custom path is available, but why don't you use a sym-link?  

In regards to performance: The performance depends on what you're trying to do.

**Comment by Ninos** [comment]
Before using a symlink I could also copy the file to the new directory. It's nearly the same for me :D Mostly all services I know support custom paths, so I think it must be also possible in pure-ftpd :)

In regards to performance, the software is thought for shared-hosting providers (hosters).

**Comment by Burnett01** [comment]
Ahh I see! 
A custom path would be nice, so Im gonna add my +support.

**Comment by Burnett01** [comment]
Hey I got something for you. What about using the --with-certfile=<file>  option?

The README quotes the following:

--with-certfile=<file>: the file with the SSL certificate (see README.TLS). The
139	default is /etc/ssl/private/pure-ftpd.pem .

**Comment by Ninos** [comment]
It's while compiling, not a really solution, because we're using already compiled packages from distro repository.. :)

**Comment by Ninos** [comment]
Ok I found following in changelog:
TLS_CERTIFICATE_FILE

I'll try it out and give feedback

**Comment by Ninos** [comment]
Ok is not working with `/etc/imscp/imscp_services.pem` in `/etc/pure-ftpd/conf/TLS_CERTIFICATE_FILE` && `/etc/pure-ftpd/conf/TLS_CERTIFICATE_PATH`

ATM I'm using Debian Jessie with pure-ftpd v1.0.36.

**Comment by Burnett01** [comment]
This might help?
https://github.com/jedisct1/pure-ftpd/blob/f0aba2e680d02722a38c2977b9c68c8c29d21eef/src/ftpd.h#L419

**Comment by Ninos** [comment]
Not really, this variables are just used while compilation. I think it must be implemented..

**Comment by Burnett01** [comment]
Mhh the only solution would be adding a new switch, as for example:

**-10  --certfile     <path>**

So it'll look like this:
```bash
/usr/local/sbin/pure-ftpd --certfile /etc/imscp/imscp_services.pem
or
/usr/local/sbin/pure-ftpd -10 /etc/imscp/imscp_services.pem
```

All the other switches/numbers are already taken. (Source: https://github.com/jedisct1/pure-ftpd/blob/f0aba2e680d02722a38c2977b9c68c8c29d21eef/configuration-file/pure-config.pl.in)

**Comment by Ninos** [comment]
Is it then also possible to add a configuration file? Think this is more important, than a new param for the daemon..

**Comment by Burnett01** [comment]
Perhaps something like that?:

CertFile          /etc/imscp/imscp_services.pem

**Comment by Ninos** [comment]
Would be very nice to have such option :)) Or may TLSCertFile / SSLCertFile :P

**Comment by jedisct1** [comment]
Done in 23e337f7d66379a303fedd159ca815d730824928

**Comment by Ninos** [comment]
Wow thanks guys!! :-)

PS: Are there any plans when the new version will be released in dist-repositories?

**Comment by jedisct1** [comment]
Released! :)

**Comment by Ninos** [comment]
Awesome
