### ISSUE TITLE
utf8 passwords in MySQL

### ISSUE THREAD

**Issue by wifibox** [jedisct1/pure-ftpd#26]
Hello,

I've had some issue in correct handling utf8 characters, like Polish chars 
(ie: łśżź).

Logins and passwords are stored in MySQL database. If anyone will set for 
virtual account login and/or password with utf8 characters - ftp login will 
failed.
I have figured out, that the problem is in MySQL client connection, which is 
initialized by Pure-FTPd. Simple patch, which solves the problem:

Patches in linked files. Hope you can use them.

http://blaszkowski.com/pubstuff/pure-ftpd/log_mysql.c.patch
http://blaszkowski.com/pubstuff/pure-ftpd/messages_en.h.patch

**Comment by jedisct1** [comment]
Hi wifibox,

Everybody is not using UTF-8, so in your case, what you actually need is make sure that the charset when inserting the data into MySQL is the same as the default one used by clients.

But more importantly: do not sure cleartext passwords. Ever.

Use `scrypt`. Or at least the best password hashing function offered by `crypt(3)` on your platform. Or at the very very very bare minimum, MySQL `PASSWORD()` function (which is terrible: it's just `'*" || SHA1(SHA1(password))`).

**Comment by wifibox** [comment]
Hello,
Thank you for reply in such short notice. As I wrote, this matter is concerning password and login. So in case handling encrypded passwords - your opinion is apposite. But wiht virtual logins I'm afraid we can not do so. 
What is your proposision for logins with international characters? If you say, that not everybody uses UTF-8, not everybody use LATIN1 either. Maybe a parameter in pureftpd-mysql.conf ?
