### ISSUE TITLE
Run without capabilities after installing rpm ?

### ISSUE THREAD

**Issue by vikas027** [jedisct1/pure-ftpd#27]
I have installed pure-ftpd rpm on a CentOS 6.6 docker container. Is there an option to run it `--without-capabilities` without rebuilding the package or please take this as a feature request. Thanks.

```bash
[root@d122438d27aa /]# rpm -qa | grep -i pure
pure-ftpd-1.0.30-1.el6.x86_64
[root@d122438d27aa /]# cat /etc/redhat-release
CentOS release 6.6 (Final)
[root@d122438d27aa /]#
[root@d122438d27aa /]# /usr/sbin/pure-config.pl /etc/pure-ftpd/pure-ftpd.conf
Running: /usr/sbin/pure-ftpd -A -c50 -B -C8 -D -fftp -H -I15 -lpam -L10000:8 -m4 -s -U133:022 -u500 -i -Oclf:/var/log/pureftpd.log -k99 -Z
421 Unable to switch capabilities : Operation not permitted
[root@d122438d27aa /]#
```

**Comment by jedisct1** [comment]
Nope, this is a compile-time feature.

**Comment by promotion** [comment]
Hi, 
this becomes VERY required feature now to do on runtime , as with porxmox 4,5 Linux containers - no pure-ftp works on VPSes (using kloxo-mr CP). Is it somehow possible ?
