### ISSUE TITLE
mac os x 10.10.4 pure-pw No useable password hashing function found

### ISSUE THREAD

**Issue by faicker** [jedisct1/pure-ftpd#29]
pure-pw useradd failed with No useable password hashing function found
OS: mac os x 10.10.4
pure-ftpd: 1.0.41

**Comment by jedisct1** [comment]
OSX doesn't have a secure `crypt(3)` implementation. The best algorithm it can do is DES, that pure-ftpd does not support any more.

You need to install [https://libsodium.org](libsodium) prior to compiling pure-ftpd in order to get a usable password hashing function.

**Comment by revolter** [comment]
@jedisct1 Is this possible using brew?

**Comment by revolter** [comment]
I found out the answer. It can be done using `brew install --build-from-source pure-ftpd`.

**Comment by toidi** [comment]
@revolter doesn't work for me

**Comment by revolter** [comment]
try running `brew uninstall pure-ftpd` before running the previous command.

**Comment by toidi** [comment]
@revolter This way it worked. Thanks.

**Comment by jedisct1** [comment]
Should be [fixed in Homebrew](https://github.com/Homebrew/homebrew-core/pull/2884)
