### ISSUE TITLE
Setting pure-authd user- and group-id while running pure-ftpd as root does not work.

### ISSUE THREAD

**Issue by web-candy** [jedisct1/pure-ftpd#3]
pure-authd creates the socket with permissions rw and launched user/group id (-u user-id and -g group-id; 1000/1000 for ftp in my case), but pure-ftpd runs as root - so it can't read/write the socket...
Maybe the socket should be created with rw/rw/rw for owner/group/others?

Workaround: chmod'ing the socket-file after launching pure-authd.

Cheers

**Comment by jedisct1** [comment]
Did you figure out what happened? root should be able to access any files.

**Comment by arekm** [comment]
Isn't that due to dropping capabilities, so CAP_DAC_OVERRIDE is gone from root and thus permissions do work even for root?

I'm currently playing with the same problem with certd where:
````
/usr/sbin/pure-certd --uid 335 --gid 335 --pid /var/run/pure-certd.pid --run /etc/pure-ftpd/certd/cert.script --socket /var/run/pure-certd/socket --daemonize
````

and

````
# ls -ldn /var/run/pure-certd/socket
srw------- 1 335 335 0 03-27 18:28 /var/run/pure-certd/socket
````

Main pure-ftpd process cannot access it anymore obviously.

What I do is hacky, racy and sucks:
````
pure-certd....
sleep 1
chown root:root  /var/run/pure-certd/socket
````

authd has the same issues as certd.

Maybe we need --socket-uid and --socket-gid options?

**Comment by jedisct1** [comment]
I don't get it. A process running as `root` cannot access a socket that is owned by a non-root account?

How is that possible?

**Comment by arekm** [comment]
root can override unix permissions only because it has proper capabilities, example:

````
# id
uid=0(root) gid=0(root) grupy=0(root),1(bin),2(daemon),3(sys),4(adm),6(disk),10(wheel)
# ls -ld testfile
-rw------- 1 arekm users 5 03-27 21:55 testfile
# cat testfile
test
# capsh --drop=cap_dac_override,cap_dac_read_search --
# LC_ALL=C cat testfile
cat: testfile: Permission denied
````

Dropped some capabilities and now permissions work for root like for any other user. 

pureftpd drops most of capabilities in in src/caps.c

**Comment by arekm** [comment]
Now it works. But giving more capabilities than needed is a bit scary.

It would be really better if authd and certd changed ownership of socket file to root:root. That way it would work and no extra capabilities would be needed. For example: dovecot (imap/pop3/... server) works that way - user can specify owner, group and mode for each socket created by dovecot daemons.

Changing authd and certd is also needed to fix unlinking of pid file. Pid file is created as root, then uid/gid gets dropped to the one specified in --uid/--gid and at the stop unlink() is done as unprivileged user, so unlink silently fails. Both xxxd daemons could fork (twice) and do the job in child while parent only task would be to change ownership of socket and unlink properly on stop.
