### ISSUE TITLE
Enable/disable account flag ?

### ISSUE THREAD

**Issue by crazy-max** [jedisct1/pure-ftpd#32]
Hi,

I currently use pureftpd-mysql on a Debian server.

Would be nice to have a sql column named for example `enabled` with int value 0 / 1 to disable / enable an account.

**Comment by jedisct1** [comment]
The config file contains SQL queries. You can change the default queries to any valid MySQL query. Just add `AND enabled = 1` to a query in the `WHERE` clause to include this column in the query.

**Comment by crazy-max** [comment]
Hum ok thanks!
