### ISSUE TITLE
SQLite support

### ISSUE THREAD

**Issue by Fnux** [jedisct1/pure-ftpd#33]
Is there a way to use/support SQLite with pure-ftpd ? (I know about puredb but I would like ot use sqlite3)

Thank you!

**Comment by jedisct1** [comment]
You can write an  [external authentication module](https://download.pureftpd.org/pure-ftpd/doc/README.Authentication-Modules).

And as a starting point, it looks like someone [already wrote one](https://github.com/oprietop/stuff/blob/master/scripts/pureftpd-sqlite-auth.sh).

**Comment by Fnux** [comment]
That's perfect ! Thank you !
