### ISSUE TITLE
pure-ftpd fails to install (Couldn't examine directory /etc/pure-ftpd/conf)

### ISSUE THREAD

**Issue by dwilson390** [jedisct1/pure-ftpd#35]
I've been having some issues with setting up pure-ftpd.  I decided to completely remove it before reinstalling it again, however I accidentally remove the configuration files before uninstalling the program with `apt-get`.  My issue is now reinstalling (or attempting to) causes the installing to fail with the following output;

    root@server:~# apt-get install pure-ftpd
    Reading package lists... Done
    Building dependency tree
    Reading state information... Done
    The following extra packages will be installed:
      libfile-copy-recursive-perl openbsd-inetd update-inetd
    The following NEW packages will be installed
      libfile-copy-recursive-perl openbsd-inetd pure-ftpd update-inetd
    0 to upgrade, 4 to newly install, 0 to remove and 2 not to upgrade.
    Need to get 0 B/277 kB of archives.
    After this operation, 929 kB of additional disk space will be used.
    Do you want to continue? [Y/n] y
    Preconfiguring packages ...
    Selecting previously unselected package libfile-copy-recursive-perl.
    (Reading database ... 54154 files and directories currently installed.)
    Preparing to unpack .../libfile-copy-recursive-perl_0.38-1_all.deb ...
    Unpacking libfile-copy-recursive-perl (0.38-1) ...
    Selecting previously unselected package update-inetd.
    Preparing to unpack .../update-inetd_4.43_all.deb ...
    Unpacking update-inetd (4.43) ...
    Selecting previously unselected package openbsd-inetd.
    Preparing to unpack .../openbsd-inetd_0.20091229-2ubuntu3_amd64.deb ...
    Unpacking openbsd-inetd (0.20091229-2ubuntu3) ...
    Selecting previously unselected package pure-ftpd.
    Preparing to unpack .../pure-ftpd_1.0.36-1.1_amd64.deb ...
    Unpacking pure-ftpd (1.0.36-1.1) ...
    Processing triggers for man-db (2.6.7.1-1ubuntu1) ...
    Processing triggers for ureadahead (0.100.0-16) ...
    Setting up libfile-copy-recursive-perl (0.38-1) ...
    Setting up update-inetd (4.43) ...
    Setting up openbsd-inetd (0.20091229-2ubuntu3) ...
     * Stopping internet superserver inetd                                                                                                                           [ OK ]
     * Not starting internet superserver: no services enabled
    Processing triggers for ureadahead (0.100.0-16) ...
    Setting up pure-ftpd (1.0.36-1.1) ...
    Starting ftp server: /usr/sbin/pure-ftpd-wrapper: Couldn't examine directory /etc/pure-ftpd/conf: No such file or directory
    invoke-rc.d: initscript pure-ftpd, action "start" failed.
    dpkg: error processing package pure-ftpd (--configure):
     subprocess installed post-installation script returned error exit status 2
    Processing triggers for ureadahead (0.100.0-16) ...
    Errors were encountered while processing:
     pure-ftpd
    E: Sub-process /usr/bin/dpkg returned an error code (1)

I have tried creating the `/etc/pure-ftpd/`, `/etc/pure-ftpd/conf/` and `/etc/pure-ftpd/auth/` directories again however this results in no configuration files actually being created and this is something I want.

How would I fully remove pure-ftpd and then reinstall it from scratch?

**Comment by jedisct1** [comment]
Maybe `apt-get purge pure-ftpd`?

This question is very specific to the Debian package, which is maintained independently, and works very differently from everywhere else.

You should really ask on a Debian forum or mailing-list instead.
