### ISSUE TITLE
Highest cipher available by default

### ISSUE THREAD

**Issue by MrUlmo** [jedisct1/pure-ftpd#36]
Why does'nt pure-ftpd choose the highest cipher available from the ciphersuite given by default?

It does default to the TLSv1.2 protocol by default.

Can I force a higher cipher, let's say  ECDHE-ECDSA-AES256-GCM-SHA384 or ECDHE-RSA-AES256-GCM-SHA384, and how?

ECDHE-ECDSA-AES256-GCM-SHA384 is not supported by the server ([WARNING] Sorry, cleartext sessions and weak ciphers are not accepted on this server.#012Please reconnect using SSL/TLS security mechanisms.) cleartext session ? weak cipher? 

openssl log:  

openssl s_client -connect 192.168.1.20:2121 -cipher ECDHE-ECDSA-AES256-GCM-SHA384 -starttls ftp
CONNECTED(00000003) 
139785619519120:error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure:s23_clnt.c:769:
- - -
no peer certificate available
- - -
No client certificate CA names sent
- - -
SSL handshake has read 345 bytes and written 149 bytes
- - -
New, (NONE), Cipher is (NONE)
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : 0000
    Session-ID:
    Session-ID-ctx:
    Master-Key:
    Key-Arg   : None
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    Start Time: 1457607756
    Timeout   : 300 (sec)
    Verify return code: 0 (ok)
- - -

And last but not less important, how can i set ECDH CURVE to secp521r1?

**Comment by jedisct1** [comment]
You need an ECDSA signed certificate to use ECDSA.

In order to change the curve, recompile with `TLS_DEFAULT_ECDH_CURVE` set to the curve you want to use. For example:

```bash
$ env CPPFLAGS=-DTLS_DEFAULT_ECDH_CURVE=secp521r1 ./configure ...
```
