### ISSUE TITLE
Missing symbol when linking with libmysqlclient.so.20

### ISSUE THREAD

**Issue by nryeng** [jedisct1/pure-ftpd#37]
log_mysql.c uses an undocumented symbol in the libmysqlclient ABI, "my_make_scrambled_password" (or, if that doesn't exist, "make_scrambled_password"). These symbols were available in libmysqlclient version 18 (MySQL 5.5 and 5.6), but have been [removed in libmysqlclient version 20 (MySQL 5.7) as part of a larger ABI cleanup](http://mysqlserverteam.com/the-client-library-part-1-the-api-the-whole-api-and-nothing-but-the-api/).

The my_make_scrambled_password function is not intended to be used by client applications, and the function signature is not available in any of the library's header files. Instead, log_mysql.c finds the function declaration in log_mysql_p.h in the Pure-FTPd source.

Please rewrite log_mysql.c to use only [the documented API of libmysqlclient](https://dev.mysql.com/doc/refman/5.7/en/c-api.html).

As a temporary fix in order to package Pure-FTPd in Ubuntu 16.04 LTS, the my_make_scrambled_password symbol has been added back to libmysqlclient in version 20.3, see [MySQL bug #80974](http://bugs.mysql.com/bug.php?id=80974), but it is deprecated and will be removed again in a future version. In order to prevent other applications from picking up a dependency on this symbol, it has not been added to the library's header files.

If you believe the functionality of my_make_scrambled_password is necessary for Pure-FTPd to work, please file a bug at http://bugs.mysql.com/ explaining why your use case is not covered by existing API functions.

**Comment by jedisct1** [comment]
Neither `my_make_scrambled_password` nor `make_scrambled_password` should be referenced at all if the symbols are not present:

```c
# ifdef HAVE_MY_MAKE_SCRAMBLED_PASSWORD
        my_make_scrambled_password(scrambled_password, password,
                                   strlen(password));
# elif defined(HAVE_MAKE_SCRAMBLED_PASSWORD)
        make_scrambled_password(scrambled_password, password);
# else
... replacement code ...
# endif
```

`HAVE_MY_MAKE_SCRAMBLED_PASSWORD` and `HAVE_MAKE_SCRAMBLED_PASSWORD` are only defined (via the autoconf script) if the symbols are available.

**Comment by jedisct1** [comment]
> Please rewrite log_mysql.c to use only the documented API of libmysqlclient.

Please read the change log from version 1.0.41 which is already pretty old:
```
- MySQL: my_make_scrambled_password() is not always an exported
symbol any more, so pure-ftpd now ships a reimplementation.
```

**Comment by nryeng** [comment]
@jedisct1 Ah, sorry to bother you, then. I looked at https://www.pureftpd.org/project/pure-ftpd/news which lists 1.0.36 as the latest version.

Thanks for the info about when this was fixed! I'll ask Debian and Ubuntu to upgrade.
