### ISSUE TITLE
Unable to start a standalone server: Permission denied

### ISSUE THREAD

**Issue by revolter** [jedisct1/pure-ftpd#38]
I installed `pure-ftpd` using `Homebrew` on OS X 10.11.4 and when I run `pure-ftpd` to start the server I get the error `Unable to start a standalone server: Permission denied`. How can I solve it?

**Comment by jedisct1** [comment]
Run it as `root` with the `sudo` command.

**Comment by revolter** [comment]
I tried that but it didn't echoed anything and I thought it's not working -_- Sorry

**Comment by frlan** [comment]
I think for non-privileged ports standalone as normal user would be a nice feature.

**Comment by jedisct1** [comment]
> I think for non-privileged ports standalone as normal user would be a nice feature.

`--with-nonroot`.

This is implemented since version 0.97.3, so it's been available for... 15 years? And it's even in the documentation :)
