### ISSUE TITLE
Login authentication failed on OS X

### ISSUE THREAD

**Issue by revolter** [jedisct1/pure-ftpd#39]
I can't get pure-ftpd to work on OS X El Capitan 10.11.4 (15E65).

I followed these steps:

    > brew install --build-from-source pure-ftpd
    > pure-pw useradd user -d ~/.ftp/user // password: test
    > pure-pw mkdb
    > sudo pure-ftpd
    > ftp user@localhost // password: test

and I get this:

    Trying ::1...
    Connected to localhost.
    220---------- Welcome to Pure-FTPd [privsep] [TLS] ----------
    220-You are user number 1 of 50 allowed.
    220-Local time is now 14:36. Server port: 21.
    220 You will be disconnected after 15 minutes of inactivity.
    331 User user OK. Password required
    Password:
    530 Login authentication failed
    ftp: Login failed
    ftp>

what am I doing wrong?

**Comment by jedisct1** [comment]
pure-ftpd supports different ways to store user information: mysql, postgresql, ldap, 3rd party scripts, local system users, as well as a tiny embedded database (puredb).

`pure-pw` creates and updates a puredb database, but by default, pure-ftpd uses local OSX accounts for authentication.

If you want to authenticate against the puredb database you created, use the `--login` option:

```sh
pure-ftpd --login=puredb:/etc/pureftpd.pdb
```

**Comment by revolter** [comment]
It actually was `pure-ftpd --login=puredb:/usr/local/etc/pureftpd.pdb`. But it works, thank you very much!

Also, is this documented anywhere?

**Comment by jedisct1** [comment]
The documentation is available here: https://www.pureftpd.org/project/pure-ftpd/doc

**Comment by jedisct1** [comment]
And the documentation related to puredb is here: https://download.pureftpd.org/pub/pure-ftpd/doc/README.Virtual-Users
