### ISSUE TITLE
checking for crypto_pwhash_scryptsalsa208sha256_str in -lsodium... no

### ISSUE THREAD

**Issue by perryao** [jedisct1/pure-ftpd#43]
Working on getting scrypt working with postgres. First started by installing libsodium and pureftpd via apt-get but wasn't able to authenticate that way. So now I'm manually downloading, extracting, and installing the tars to see if I can track down the issue. When I run `./configure` inside of the pure-ftpd directory, I get the following message: 

`checking for crypto_pwhash_scryptsalsa208sha256_str in -lsodium... no`

Is there a specific flag I need to pass to libsodium to get this check to pass? The scripts I'm using to install both are below (using Docker hence the Run commands):

OS: debian:jessie

Versions:
libsodium: 1.0.10
pure-ftpd: 1.0.41

```
RUN mkdir /usr/src/libsodium \
    && cd /usr/src \
    && curl -SOL "https://download.libsodium.org/libsodium/releases/libsodium-1.0.10.tar.gz.sig" \
    && curl -SOL "https://download.libsodium.org/libsodium/releases/libsodium-1.0.10.tar.gz" \
    && tar -xzf libsodium-1.0.10.tar.gz -C /usr/src/libsodium --strip-components 1 \
    && cd /usr/src/libsodium \
    && ./configure \
    && make \
    && make check

RUN mkdir /usr/src/pure-ftpd \
    && cd /usr/src \
    && curl -SOL "https://download.pureftpd.org/pub/pure-ftpd/releases/pure-ftpd-1.0.41.tar.gz" \
    && tar -xzf pure-ftpd-1.0.41.tar.gz -C /usr/src/pure-ftpd --strip-components 1 \
    && cd /usr/src/pure-ftpd \
    && ./configure --with-pgsql --with-tls \
    && make install-strip
```

/etc/pureftpd-pgsql.conf

```
PGSQLServer     $PG_HOST
PGSQLPort       $PG_PORT
PGSQLUser       $PG_USER
PGSQLPassword   $PG_PASS
PGSQLDatabase   $PG_DB
PGSQLCrypt      any
PGSQLGetPW      SELECT "Password" FROM "users" WHERE "User"='\L'
PGSQLGetDir     SELECT "Dir" FROM "users" WHERE "User"='\L'
PGSQLDefaultGID 1000
PGSQLDefaultUID 1000

```

And finally I'm running pureftpd like so: 

`/usr/local/sbin/pure-ftpd -c 50 -C 10 -l pgsql:/etc/pureftpd-pgsql.conf -A -E -j -R -d -P $PUBLICHOST -p 30000:30009`

**Comment by jedisct1** [comment]
Hi there.

Looks like the `libsodium` installation is missing `make install` and `ldconfig`!

**Comment by perryao** [comment]
whoa fast response. Thanks :) Looks like I have ldconfig here: /sbin/ldconfig. Are you saying I should just add `make install` and `ldconfig` at the end of the libsodium installation? like so: 

```
RUN mkdir /usr/src/libsodium \
    && cd /usr/src \
    && curl -SOL "https://download.libsodium.org/libsodium/releases/libsodium-1.0.10.tar.gz.sig" \
    && curl -SOL "https://download.libsodium.org/libsodium/releases/libsodium-1.0.10.tar.gz" \
    && tar -xzf libsodium-1.0.10.tar.gz -C /usr/src/libsodium --strip-components 1 \
    && cd /usr/src/libsodium \
    && ./configure \
    && make \
    && make check \
    && make install \
    && ldconfig
````

**Comment by jedisct1** [comment]
Exactly. Or you can use the full `/sbin/ldconfig` path if you like.

**Comment by perryao** [comment]
Awesome that worked. Had to use `/sbin/ldconfig`. Didn't work with just `ldconfig`. Thanks again.
