### ISSUE TITLE
Syntax error on server start

### ISSUE THREAD

**Issue by velinath** [jedisct1/pure-ftpd#48]
Hello,

Using CentOS 7 on a fresh compile of pure-ftpd 1.0.44, I get the error "syntax error: [CipherSuite HIGH]" when attempting to enable TLS on the server. I've tried changing the TLSCipherSuite to any number of valid OpenSSL cert strings, and they all throw a syntax error.

Commenting out the line does work, and properly serves the certificate, so I don't think I'm missing a command-line compile option. My ./configure:

`./configure --prefix=/usr --bindir=/usr/bin --sbindir=/usr/sbin --libexecdir=/usr/libexec --datadir=/usr/share --sysconfdir=/etc/pure-ftpd --sharedstatedir=/usr/com --localstatedir=/var --libdir=/usr/lib64 --includedir=/usr/include --infodir=/usr/share/info --mandir=/usr/share/man --with-pam --with-tls --with-virtualchroot --with-everything`

**Comment by jedisct1** [comment]
Hi,

And thanks for reporting this. Indeed, this was a bug in the parser, fixed here: https://github.com/jedisct1/pure-ftpd/commit/3823d00dee089b998d1f40943e9aa3f619c238b2

But you will get a more secure cipher suite by *not* setting `TLSCipherSuite` to `HIGH` and just leaving the default.

**Comment by velinath** [comment]
Thank you so much! Appreciate the clarification and the fix. :)

**Comment by jedisct1** [comment]
Appreciate the bug report :)
