### ISSUE TITLE
Error message when userid < 1000

### ISSUE THREAD

**Issue by LDA-IT** [jedisct1/pure-ftpd#49]
Hello,

If the system user mapped by the FTP user has a uid/gid < 1000, it seems that:  
- there is no warning or error when creating an FTP user with **pure-pw useradd**
- the error message in the log is less than explicit: **[WARNING] Can't login as [joe]: account disabled**

Could we get an explicit warning or an error when creating the FTP user or in the message log?

Thanks,
Jérôme

**Comment by jedisct1** [comment]
Hi,

`pure-pw` has no knowledge of the pure-ftpd configuration, and cannot infer what the minimum uid will be, if any.

The error message has been clarified in efd620365a8ea0d30837a412a3e4c2ee71e279d2

Thanks for suggesting this!
