### ISSUE TITLE
 syntax error line 425: [CipherSuite

### ISSUE THREAD

**Issue by SchnorcherSepp** [jedisct1/pure-ftpd#51]
If i use the default config and folow the documantation, this error happend with active TLS.

```
/etc/pure-ftpd.my.conf:425:4: syntax error line 425: [CipherSuite               HIGH].
421 Configuration error
```

If I do not use the TLSCipherSuite option, then everything works fine:
`#TLSCipherSuite               HIGH`

My setup:

- `pure-ftpd v1.0.44 [privsep]`
- `./configure --with-altlog --with-tls --with-puredb --with-rfc2640`

**Comment by jedisct1** [comment]
Duplicate of https://github.com/jedisct1/pure-ftpd/issues/48

Sorry for that. I am going to release 1.0.45 soon.
