### ISSUE TITLE
Inform clients to issue passive commands over the same host they used to connect.

### ISSUE THREAD

**Issue by perryao** [jedisct1/pure-ftpd#54]
We have what may be a somewhat unusual deploy for pureftpd. We're running two publicly accessible load balancers using HAProxy, with DNS round robin setup to "load balance" between the two public proxies. Both are setup to proxy to pureftpd. The problem we're having is we need clients to just assume that all subsequent passive commands should be executed over the same IP they used to authenticate. I can't use the --force-passive-ip option because that will break TLS if I respond with the IP of the other proxy.

Using curl, I can specify to ignore the passive ip provided by the server like this:

`curl -v -k --ftp-ssl --disable-epsv --ftp-skip-pasv-ip --user USER:PASS ftp://ftp.example.com`

Other clients like filezilla, lftp, and Transmit on iPhone all seem to default to ignore unreachable hosts in the response for passive commands. But we have one customer using a client that isn't capable of specifying as much.

Here's a rough diagram of this setup:

```
               Proxy 1 (75.xx.xx.xx)

INTERNET --->                       ----> pureftpd(172.xx.xx.xx)

                Proxy 2 (54.xx.xx.xx) 
```
P.S. @jedisct1 I sent this through list-subscribe@pureftpd.org but it seems the archives page at http://archives.pureftpd.org/archives.cgi?100 is giving a 500 error. Is github issues or the mailing list the best place for things like this?

**Comment by jedisct1** [comment]
Hi!

The mailing-list remains a good place for things like this, but Github may be even better to reach out to me directly :)

Making FTP servers and load-balancers play well with each other is indeed quite tricky.

In your setup, may the cleanest way to solve this would be to add a new feature, that would return a passive IP according to a map:

```
<Proxy 1 internal ip> -> <External IP of Proxy 1>
<Proxy 2 internal ip> -> <External IP of Proxy 2>
```

Would that work for your specific case?

**Comment by perryao** [comment]
So say user connects to ftp.example.com. Based on the DNS round robin we have set up, that might resolve to 75.xx.xx.xx or 54.xx.xx.xx. Would this solution ensure that for subsequent passive commands, they're being sent to the same IP initially used to authenticate?

**Comment by perryao** [comment]
Based on rfc 2428 (https://www.ietf.org/rfc/rfc2428.txt?number=2428) it sounds like I'm wanting EPSV mode. With that mode, only the port is provided in the PASV response.

**Comment by jedisct1** [comment]
There are three ways for a client to ask the server to return the address of the data socket to connect to:

- PASV
- EPSV
- SPSV

Pure-FTPd supports them all.

`EPSV` and `SPSV` don't include an IP address. The client just connects to the original connection IP.

But the *client* picks the command it wants to use. Most modern clients use `EPSV` because `PASV` is incompatible with IPv6.

If the customer's client sends `PASV`, it's very likely that it doesn't support `EPSV`.
And even if it does, disabling `PASV` in the server is unlikely to have it retry using `PASV`.

You can still check if that client cannot be forced to send `EPSV` or `SPSV`. But server-side, we can't force it to do so.

**Comment by perryao** [comment]
Thanks for the great explanation. I just confirmed that their client doesn't support EPSV (an old Windows enterprise app). So how might your mapping idea help in this scenario? What I think I need is a way for pureftpd to dynamically provide the PASV IP (instead of just provided as a runtime argument). But I'd still need to know which proxy the client originally connected through in order for TLS to terminate properly, and that's the part I'm not sure can be done.

**Comment by jedisct1** [comment]
With the map, the server would return a PASV IP based on the load balancer IP, instead of returning the server external address, or a static IP.
