### ISSUE TITLE
Unrouteable IP on PORT Command

### ISSUE THREAD

**Issue by WyTech** [jedisct1/pure-ftpd#55]
I have an edge case here where the client is in Active mode, doesn't support Passive, uploading files, and passes an internal private unrouteable IP on the PORT command which causes: 500 I won't open a connection to 10.28.14.115 (only to XX.123.45.67)

I don't have direct control over the remote sender config.  

I've been thru all the settings and there doesn't seem to be an override for this.  If I bypass the PORT warning, it still fails on the transfer attempt when the client initiates their upload.

It would be useful to have a setting that would try the original connection address in place of the unrouteable address in the event of failure.

**Comment by jedisct1** [comment]
Looks like a badly configured router/NAT gateway. That `PORT` command probably comes from that device and not from the original client.

Ignoring the PORT connection is really an unusual case, and not really a feature that can be merged to the main branch.

But commercial support for pure-ftpd is available, and can include custom additions like that one, that will always get ported to later versions.

**Comment by WyTech** [comment]
That's possible, as it is behind a NAT/firewall.  Client or NAT, really doesn't matter.  But something on their end isn't providing a routeable address.  The way this is normally dealt with is to query to NAT's outside address using a web service and then apply it to the client request.  This is the way FileZilla and some other clients deal with NAT configs.  The client in question is a legacy FTP app and their current technical staff doesn't seem to have the skill set to fix/comprehend it.  

We resolved our issue by reversing roles and using their FTP server. 

My suggestion wasn't to ignore the PORT command, but to have the option to failover to the connection IP in the event the PORT IP connection fails and the address is in the reserved private ranges.

**Comment by jedisct1** [comment]
I meant ignoring the IP specified in the `PORT` command, and use the connection IP instead.

But well, reversing the roles also works :)

Glad to hear that you found a workaround.  NAT never plays well with the FTP protocol and is often the source of complications :(

Cheers!
