### ISSUE TITLE
Weird behavior while using Google cloud bucket storage 

### ISSUE THREAD

**Issue by skechboy** [jedisct1/pure-ftpd#56]
Hello, 

I've noticed some very weird issue while using pure-ftpd on a Google cloud storage mounted system. The issue occurs when I'm trying to delete file from the ftp directory.  Here is the error message I receive from the server: 

`
Status:	Deleting "/test.txt"
Command:	DELE test.txt
Response:	550 Could not delete test.txt: Invalid argument
`
Once I see this error message I can see that the file is "removed" but what happens really it is renamed under following name: .pureftpd-rename....

I'm using Google cloud storage mounted as regular partition using gcsfuse from @jacobsa, I'm able to create, modify delete files directly trough the server using the corresponding users so we can exclude permission issue here. Also I'm able to upload and rename files trough FTP on gcsfuse mounted partition. I've tested the same setup on the same server on a local mounted partition and  everything works fine.

My initial observation is that pure-ftpd is having some issue due to delay of several milliseconds in gcsfuse mounted partitions. The delay is due to to the fact that gcsfuse partitions are network mounted partitions, and also the type of the cloud storage I'm using is mainly for write operations meaning reading from it is quite slow. 

My question is if there is any way we can solve this trough setting or if not maybe you can point me to some direction where to modify the source of pure-ftpd in order to solve this. 

Thanks

**Comment by jedisct1** [comment]
Maybe this happens because when using this FUSE filesystem, renaming a file is not atomic, and actually creates a new file instead of changing the name of the existing one.

You can try to comment out this code snippet, from `src/ftpd.c`. It might help.

```c
        if (lstat(qtfile, &st2) != 0 ||
            st.st_dev != st2.st_dev ||
            st.st_ino != st2.st_ino ||
            st.st_size != st2.st_size) {
# ifdef EINVAL
            errno = EINVAL;
# endif
            goto denied;
        }
```

**Comment by skechboy** [comment]
Yes, I can confirm that some metadata operations especially "rename" on FUSE filesystem are not atomic. 

I will try your recommendation. 

Thanks

**Comment by jedisct1** [comment]
pure-ftpd generally expects POSIX semantics. You may have issues with quotas as well (unless you're not using them).

**Comment by skechboy** [comment]
Removing the code sniped you've mentioned solved the problem with the delete. It turned out that gcsfuse supports atomic rename on files but not on directories, which is OK for my intended use. 

Also I've tested virtual quotes in combination with mysql and they worked fine.

Thanks a lot for your help.

**Comment by platinum55** [comment]
I have the same problem with GCSF now, but removing the code mentioned didnt help, any ideas?

550 Could not delete <file>: No such file or directory

tried with the latest code from here
