### ISSUE TITLE
dynamicbase breaks cygwin build

### ISSUE THREAD

**Issue by matzeri** [jedisct1/pure-ftpd#57]
After some chasing I found that the LDFLAGS = -Wl,--dynamicbase is not really compatible with 
latest cygwin compilers.
Two main issues:
- 32bit version is unable to fork properly
- 32bit and 64bit binaries are crippled and GDB is unable to properly set breakpoint.

https://cygwin.com/ml/cygwin/2017-05/msg00077.html

[pure-ftpd-noroot.patch.txt](https://github.com/jedisct1/pure-ftpd/files/987081/pure-ftpd-noroot.patch.txt)

**Comment by jedisct1** [comment]
Unfortunately, the statement from the `README.Windows` file still holds true: Cygwin is completely unsupported.

I almost never use Windows, and even less Cygwin. Nobody is actively working on a serious Windows port.

The `dynamicbase` flag can be removed if it causes issues with current Cygwin versions, but any other changes, especially anything that tries to go beyond the non-root mode, will probably not be merged.

**Comment by matzeri** [comment]
The proposed change is limited to dynamicbase as it is defined only for Cygwin build and it produces unexpected consequence.

I am aware that Cygwin is not supported, and the current cygwin package
https://cygwin.com/ml/cygwin-announce/2017-05/msg00027.html
 have some hacks that were put in place by my predecessor as package maintainer. 
 I don't like them too much, so I am not proposing them to you in the current form.

**Comment by jedisct1** [comment]
`dynamicbase` was removed!

Thanks a lot for pointing this out!
