### ISSUE TITLE
my_make_scrambled_password() is not equivalent to make_scrambled_password()

### ISSUE THREAD

**Issue by panlinux** [jedisct1/pure-ftpd#58]
From https://github.com/jedisct1/pure-ftpd/blob/master/src/log_mysql.c#L470:

```
 char scrambled_password[42]; /* 2 * 20 (sha1 hash size) + 2 */

# ifdef HAVE_MY_MAKE_SCRAMBLED_PASSWORD
        my_make_scrambled_password(scrambled_password, password,
                                   strlen(password));
# elif defined(HAVE_MAKE_SCRAMBLED_PASSWORD)
        make_scrambled_password(scrambled_password, password);
# else
 ( internal implementation )
```

That buffer is declared with a fixed size as is expected by the `make_scrambled_password()` function in libmysqlclient.
If `make_scrambled_password()` is not available and `my_make_scrambled_password()` is, though, then `scrambled_password `will overflow, as `my_make_scrambled_password()` is something entirely different which uses `my_crypt_genhash()` and will write length `CRYPT_MAX_PASSWORD_SIZE` to `scrambled_password`:
```
void my_make_scrambled_password(char *to, const char *password,
                                size_t pass_len)
{

  char salt[CRYPT_SALT_LENGTH + 1];

  generate_user_salt(salt, CRYPT_SALT_LENGTH + 1);
  my_crypt_genhash(to,
                     CRYPT_MAX_PASSWORD_SIZE,
                     password,
                     pass_len,
                     salt,
                     0);

}
```
The mysql client library wraps `make_scrambled_password()` around `my_make_scrambled_password_sha1()`, not `my_make_scrambled_password()`. Note the confusion in the docstring as well, where it omits the `_sha1()` suffix probably by mistake (https://github.com/mysql/mysql-server/blob/5.7/sql/auth/password.c#L254):
```
/*
  Wrapper around my_make_scrambled_password() to maintain client lib ABI
  compatibility.
  In server code usage of my_make_scrambled_password() is preferred to
  avoid strlen().
  SYNOPSIS
    make_scrambled_password()
    buf       OUT buffer of size 2*SHA1_HASH_SIZE + 2 to store hex string
    password  IN  NULL-terminated password string
*/

void make_scrambled_password(char *to, const char *password)
{
  my_make_scrambled_password_sha1(to, password, strlen(password));
}

```

Finally, even if by some reason the overflow doesn't happen, the content is very much different than what is stored on the server side by using the PASSWORD() sql function, as that stores "*<hexstring>" and not a hash as returned by `my_make_scramble_password()`.

**Comment by jedisct1** [comment]
Thanks for pointing this out. This API is quite confusing and bogus comments don't help :/

The internal implementation is now used unconditionally. This will prevent further surprises, although this hashing method (along with md5/sha1) is likely to be removed soon.

Thanks!
