### ISSUE TITLE
CWD command

### ISSUE THREAD

**Issue by dpolyakov** [jedisct1/pure-ftpd#60]
I`m using pure-ftpd-mysql on my server.
And i want to upload screenshots, which taked with [Monosnap](http://monosnap.com).

Monosnap can`t validate ftp settings. I looked in logs:
```console
Jun  6 17:17:08 servr pure-ftpd: (?@*.*.*.*) [INFO] New connection from *.*.*.*
Jun  6 17:17:08 servr pure-ftpd: (?@*.*.*.*) [DEBUG] Command [user] [pic]
Jun  6 17:17:08 servr pure-ftpd: (?@*.*.*.*) [DEBUG] Command [pass] [<*>]
Jun  6 17:17:08 servr pure-ftpd: (?@*.*.*.*) [INFO] pic is now logged in
Jun  6 17:17:08 servr pure-ftpd: (pic@*.*.*.*) [DEBUG] Command [syst] []
Jun  6 17:17:08 servr pure-ftpd: (pic@*.*.*.*) [DEBUG] Command [pwd] []
Jun  6 17:17:08 servr pure-ftpd: (pic@*.*.*.*) [DEBUG] Command [type] [I]
Jun  6 17:17:08 servr pure-ftpd: (pic@*.*.*.*) [DEBUG] Command [cwd] [/var/www/__pic/]
Jun  6 17:17:08 servr pure-ftpd: (pic@*.*.*.*) [INFO] Logout.
```
I connected to my ftp server, and checked all commands, and find that `cwd` is invalid command for PureFtpd:
```console
ftp> cwd
?Invalid command.
```

Can you help me?

**Comment by jedisct1** [comment]
pure-ftpd understands the `cwd` command.

Within your FTP client, you probably have to type `cd` in order to send this command, not `cwd`.

Are the two dashes before the `pic` directory name expected? Does the `/var/www/__pic` directory exist?

**Comment by dpolyakov** [comment]
Directory `__pic` is exist and writeblle.

>Within your FTP client, you probably have to type cd in order to send this command, not cwd.

Yes. It was my mistake. I thinked that `help` show me list of commands, which supported by ftp server.

I tried another ftp-client, and all works fine. Problem only with Monosnap :(
