### ISSUE TITLE
Throttling of Unix users (virtual users not affected)

### ISSUE THREAD

**Issue by tmcdos** [jedisct1/pure-ftpd#62]
I tried 3 different versions - 1.0.36/42/46, all of them are compiled using the same parameters:

```
export CFLAGS="-march=native -m64 -O2 -pipe -fomit-frame-pointer -fgcse -Os -L/usr/local/mysql/lib"
./configure --prefix=/usr/local --without-inetd -with-altlog --with-mysql=/usr/local/mysql \
--with-peruserlimits --without-quotas --without-capabilities --without-humor --without-ascii --with-rfc2640
```
As you see, I have not enabled throttling at all.
My configuration is attached.
When I log in as a virtual user - I am able to download with about 8 MB/s.
But when I log in as a Unix user - I am able to download with no more than 5 MB/s.
The behavior is consistent. OS is CentOS 7, 64-bit.
Any ideas for troubleshooting ?
[pure-ftpd.conf.txt](https://github.com/jedisct1/pure-ftpd/files/1152297/pure-ftpd.conf.txt)
[pure-mysql.conf.txt](https://github.com/jedisct1/pure-ftpd/files/1152298/pure-mysql.conf.txt)

**Comment by jedisct1** [comment]
Are you downloading the exact same file? After is has been cached?

Make sure that you are starting the executable you compiled and not some other version.

The config files has references to `pureftpd-wrappers.pl` but that script doesn't exist any more.
Try running directly `/path/to/pure-ftpd /path/to/config/file`.

**Comment by tmcdos** [comment]
I login as Unix user, upload a file, then logout, login as virtual user and download the file - downloading speed is more than 8 MB/s.
I then upload another (new) file, then logout, login as Unix user (same as before) and download the new file - downloading speed is no more than 5 MB/s.

I am sure I am running the compiled executable - I checked with "strings /usr/local/sbin/pure-ftpd | grep Software" and the SystemD service file explicitly uses the full pathname to this executable.

Config file is the same for 1.0.36, 1.0.42 and 1.0.46 - but the former 2 require the usage of "pure-config.pl" and the latter one does not.

Any other ideas ? Perhaps providing you with login credentials to test ?

**Comment by tmcdos** [comment]
Caching does not seem an issue because if I login as virtual user, download a file (with 8 MB/s) then logout and login as Unix user and start downloading the same file - speed is capped at 5 MB/s.

**Comment by tmcdos** [comment]
Hmm, I tried both passive and active transfers and it seems the issue is only with passive ones ...

**Comment by jedisct1** [comment]
The test doesn't look reliable. You should try downloading the exact same file.

Also watch the `iostat` output; maybe the disk isn't keeping up.

The code that sends files doesn't know what user is logged in, and is the same in passive and active mode.

Maybe you have firewall rules for specific users?

Off the top of my head, I don't see anything in pure-ftpd that would lead do this, especially since you didn't even compile support for throttling.
So I can't help any further, sorry.

**Comment by tmcdos** [comment]
I tried downloading the same file, using 2 different FTP clients.

**Comment by jedisct1** [comment]
Passive connections are matched by a specific rule in your firewall configuration. This has a cost.

Also, the range of ports allocated to passive FTP data connections should be way larger than 24. The smaller, the less secure your server is.

**Comment by tmcdos** [comment]
> Passive connections are matched by a specific rule in your firewall configuration. This has a cost.
Well, port 80 has a similar rule - but I am able to download the exact same file through nginX with a speed of 7.5 MB/s

> Also, the range of ports allocated to passive FTP data connections should be way larger than 24. The smaller, the less secure your server is.
I am the only one who uses this server - it is a development machine.

Okay, I see I am on my own with this issue. I would like to thank you for your time and the empathy ...
