### ISSUE TITLE
Bugfix release for MariaDB 10.2 update

### ISSUE THREAD

**Issue by kevin-olbrich** [jedisct1/pure-ftpd#64]
Hi,

there is great demand for users of pure-ftpd-mysql in Debian 8 / 9 when MariaDB 10.2 instead of 10.1 is installed:
https://jira.mariadb.org/browse/MDEV-12889
https://github.com/jedisct1/pure-ftpd/commit/27443b29320d85352d8b52c0120836843e10c0f9

It would be nice to have this packages and rolled out to debian 8 / 9 repos.

Kind regards,
Kevin

**Comment by jedisct1** [comment]
Well, this is something Debian maintainers could do, not me :)
