### ISSUE TITLE
feature request: -lpuredb user expiry

### ISSUE THREAD

**Issue by lkarsten** [jedisct1/pure-ftpd#65]
Hello.

I want to request calendar/time based user expiry for (virtual) puredb users.

Please excuse me if this is a FAQ or has been discussed earlier. I was not able to find anything of the sort when searching for it.

I'm using pure-ftpd to provide paid FTP access. Typically access lasts for two or three weeks, and the user account should be disabled afterwards. I'm currently managing this manually with some scripts, but an integrated solution would be better.

There are probably many options wrt. using ldap or a sql authentication backend, but I prefer the simplicity of puredb. -lpam is of course also an option, but then the line between virtual users and the system is blurred. I understand if this line seems arbitrary for anyone but me.

Having looked briefly at the code, I think this could be done through adding a unixtime field last in `pure-ftpd.passwd`. Extending pure-pw and pw_puredb_parseline() in `log_puredb.c` seems to be the main code paths. Older parsers won't read/strtok the extra field, giving a semi-reasonable upgrade and downgrade paths.

If this is something to be considered for merging later on, I'm happy to suggest a patch/pull-request that implements this. Please advise.

**Comment by jedisct1** [comment]
Hi!

Adding and checking a timestamp is indeed a good way to achieve this.

However, I'm not sure that this is something that should be merged. pure-ftpd has been around for 16+ years and as far as I know, this is the first time ever such a feature is requested :)
OTOH, there are probably quite a few people using  scripts to directly build/parse the `pure-ftpd.passwd` file that may then break.

So... I'm not sure :) Maybe wait until more people ask for that feature?

**Comment by lkarsten** [comment]
Hi. Thanks for responding.

I'm partial to your argument. If it is only I that needs this, then it isn't worth the extra code to maintain. Since people can fix it with scripts/cron (as I have for the last 3-4 years), maybe that is sufficient.

That being said, having briefly seen the -z option earlier I was pretty much convinced this was in there and I was just initially not able to find it. It seems like a natural feature for me.

Would you consider keeping the issue open for a while and seeing if someone else cares to comment?

**Comment by jedisct1** [comment]
Thank you for being so understanding!

Yep, let's keep the issue open!
