### ISSUE TITLE
Recursive symlinks lead to file deletion and data loss after failed RETR command

### ISSUE THREAD

**Issue by robertmathews** [jedisct1/pure-ftpd#68]
If a directory contains files plus a symlink to itself, created like so:
```
echo testfile > testfile
ln -s ./ test
```
... and you then download a file like this:
```
CWD /test/test/test/test/test/test/test/test/test/test/test/test/test/test/test/test/test/test/test/test/test

RETR testfile
````
... (which can happen if you use something like wget in recursive mode), pure-ftpd will send:
```
[ERROR] realpath() failure : [testfile] => [Too many levels of symbolic links]
````
... and then it will delete the file in question from the server (!).

This happens because displayrate() in src/ftpd.c contains an "unlink()" at line 2851:

https://github.com/jedisct1/pure-ftpd/blob/master/src/ftpd.c#L2851

I suspect the unlink() is there to clean up after a failed upload, but it doesn't seem like it should be called for a failed download.

**Comment by jedisct1** [comment]
I guess the original intent was to clean up the situation as soon as possible. Symlink loops can easily lead to a denial of service.

Anyway, this has been changed to only delete the link on uploads.
