### ISSUE TITLE
Config file and options cannot be together on the command line

### ISSUE THREAD

**Issue by olysonek** [jedisct1/pure-ftpd#69]
Pure-ftpd doesn't allow having both a configuration file and options on the command line. This makes it impossible for packagers to create reliable init scripts and systemd service files - the problem is that the packager cannot set the daemonization parameter.

In Debian, this is solved by keeping a modified version of the pure-config.pl wrapper. In other distros I checked (e.g. Arch Linux, openSUSE), the packagers decided to rely on what the user puts in the configuration file. But I really don't want to do that. The main problem with it is that the default for the daemonization setting built in to the daemon is 'false', whereas the value of this setting in the default configuration file is 'true'. If the user decides to write their own config file from scratch, they might not notice that they need to set 'Daemonize=true'.

So there needs to be a way for a packager to override the daemonization setting, otherwise the pure-ftpd service will fail mysteriously, if not configured as expected. I already have a patch in Fedora which allows having both a config file and options on the command line, I'll be happy to send it to you. But I first wanted to know your thoughts on the subject, because of what it says in README.Configuration-File [1]:
"    /usr/local/sbin/pure-ftpd /etc/pure-ftpd.conf

Note the absence of switches. In order to avoid confusion, either a
configuration file or a set of command-line switches can be used."

I believe the convention in other projects generally is that command line options override settings in a configuration file. I find that to be very reasonable.

[1] https://github.com/jedisct1/pure-ftpd/blob/master/README.Configuration-File#L30-L31

**Comment by jedisct1** [comment]
That is completely intentional. Having different ways to provide potentially incompatble options is confusing and potentially dangerous.

Consider the list of authentication methods for example. The order is important. This is a list, and method are tried in sequence.

It also makes it more difficult to troubleshoot user issues.

People are unlikely to write a configuration file from scratch. They will modify the existing one. You can add a comment above the `Daemonize` option on the fact that changing this would not play well with the systemd service provided by the distribution.

**Comment by arekm** [comment]
It breaks setups where init.d script passes conditional options like in my case:

daemon /usr/sbin/pure-ftpd /etc/ftpd/pureftpd.conf \
                                $([ "$PURE_AUTH" = "yes" ] && echo "-lextauth:$PURE_AUTH_SOCKET") 

It's inconsistent with almost every daemon software I know and it's totally unexpected by system user/admin.

Thanks for Fedora patch, I'll use it in PLD, too.

**Comment by olysonek** [comment]
> It's inconsistent with almost every daemon software I know and it's totally unexpected by system user/admin.
>
> Thanks for Fedora patch, I'll use it in PLD, too.

I completely agree. But note that the patch was a quick midnight hack, there's definitely room for improvement.
