### ISSUE TITLE
TLS 1.0

### ISSUE THREAD

**Issue by Ressy66** [jedisct1/pure-ftpd#71]
I know 1.0 was disabled by default as of 1.0.45
But have a client who wants to use 1.0.47 but for their reasons are unable to upgrade openssl so are limited to 1.0, how do we re-enable this for them?  

Edited: It seems readme.tls needs updating too, there's no mention of it and talks about ancient versions :)

**Comment by jedisct1** [comment]
I morally can't support such a horrible thing.

**Comment by racke** [comment]
I second this decision 👍

**Comment by Ressy66** [comment]
So you'd rather them use just plain text :)  Thats what they've just told me to do and if that is ended, well, I wont repeat what they said lol
Thanks anyway.
