### ISSUE TITLE
Virtual hosts for passive mode over LAN?

### ISSUE THREAD

**Issue by kaysond** [jedisct1/pure-ftpd#73]
Is there a way to have pure-ftpd respond to PASV with its LAN ip address for local clients, and a different ip address for external clients? With forcepassiveip set to the external ip (which I need to connect from outside my network) LAN connections have to go through the router's nat loopback which limits the throughput.

**Comment by jedisct1** [comment]
The main advantage of not supporting virtual hosts that way is that it keeps the configuration very simple. Having distinct instances has no overhead on modern operating systems, and offers more flexibility and security.

OpenBSD firewalls have an ftp_proxy component that will rewrite PASV reponses for hosts behind NAT, and I'm sure the same thing can be achieved on Linux with nftables and ip_conntrack_ftp. But indeed, that wouldn't work over TLS.

**Comment by kaysond** [comment]
Makes sense. Thanks.
