### ISSUE TITLE
Self-Compiling: missing -mysql and -mysql-virtualchroot

### ISSUE THREAD

**Issue by Hirbod** [jedisct1/pure-ftpd#76]
Hi,

as an application forced me to upgrade MariaDB to 10.2, I was having problems with my ISP Panel. I spent like 6 hours to fix this by my own but I'm going to give up. I've compiled from source but after I'm done, there is no binary "pure-ftpd-mysql" or "pure-ftpd-mysql-virtualchroot" which will be installed if I use "apt install pure-ftpd-common pure-ftpd-mysql". "pure-ftpd" and other binaries are compiled. I also used the right configure-flags.

I know this is no support forum but I really tried everything to get this self-compiled version to run in order to have support for FTP in my Panel ISPConfig.

There isn't any good documentation about this and I got stuck. Debian Stretch.

Any advice how I could get this whole thing work again?

**Comment by jedisct1** [comment]
Debian made some changes to build differently named binaries for different builds.

But if you compiled it yourself with `--with-mysql`, the resulting binary is simply called `pure-ftpd`.

**Comment by Hirbod** [comment]
Hi, thanks so far. Do you have any working init-script / service? Using those from the .deb file showing "active (exited)" when starting.

**Comment by jedisct1** [comment]
Ah no, sorry, I use a Mac.
