### ISSUE TITLE
Hide version when nmap

### ISSUE THREAD

**Issue by stef157** [jedisct1/pure-ftpd#81]
Hi,
For some security purpose, I wanted to know how it was possible to hide the service name ?
When I've made an nmap… the pure-ftpD was show and I prefer to hide it…

Thanks.

**Comment by jedisct1** [comment]
It's only for folklore, not security, as you can just probe supported features and error codes to find what version is running. `ftpmap` does that automatically.

Anyway, `--with-boring` hides the server name and version number.
