### ISSUE TITLE
Problems with PureDB authentication after upgrade from 1.0.42 to 1.0.46

### ISSUE THREAD

**Issue by olysonek** [jedisct1/pure-ftpd#82]
We received a bug report in Fedora [1] that PureDB authentication stopped working after upgrade from 1.0.42 to 1.0.46. I haven't been able to reproduce it and I don't really have any details about it. So just a question: are you aware of any changes that might have caused this? Are there any known issues? I've gone through the changelog, but haven't found anything.

Thanks.

[1] https://bugzilla.redhat.com/show_bug.cgi?id=1490354

**Comment by jedisct1** [comment]
Try to apply this: https://github.com/jedisct1/pure-ftpd/commit/27a5c200f9643ce907118aad169279b3a66a9e8a

**Comment by BlackYoup** [comment]
Hello,

This commit solves this issue :) Would it be possible to have a release that includes it?
