### ISSUE TITLE
pure-ftpd config parsing

### ISSUE THREAD

**Issue by grubberr** [jedisct1/pure-ftpd#84]
Hello,

I have a question
in the latest pure-ftpd versions where pure-config.pl script was removed
config now parsed by main pure-ftpd binary
it's not very clear for me how it works:

does it support both config file and command line options simultaneously ?

``
/usr/sbin/pure-ftpd /etc/pure-ftpd.conf --daemonize
``

it looks like - no :(

I want to provide config file and force --daemonize in command line options ( even if in config file 'Daemonize no' )

is it possible to do ?

Thanks

**Comment by jedisct1** [comment]
To avoid confusion, options are either provided on the command line, or in the configuration file.
