### ISSUE TITLE
Unable to run Pure-FTPd with OpenSSL 1.0.2n on ubuntu 14

### ISSUE THREAD

**Issue by jignesh1992** [jedisct1/pure-ftpd#87]
I am trying to compile Pure-FTPd 1.0.47 with OpenSSL 1.0.2n.

Though the compiling finishes without any error, but it does not work. When I try to start or restart from the command line on ubuntu 14, I get the following error:
Starting pure-ftpd: /usr/local/apps/pureftpd/sbin/pure-ftpd: symbol lookup error: /usr/local/apps/pureftpd/sbin/pure-ftpd: undefined symbol: DH_get_2048_256
[ OK ]

I am unable to debug or make sense even after googling for hours.

In case if something is wrong with my pure-ftpd configure command you can check it below:

```
LDFLAGS="-L$PPS_PATH/lib" CPPFLAGS="-I$PPS_PATH/include" LD_LIBRARY_PATH="$PPS_PATH/lib" ./configure 
--prefix=$PATH_PUREFTPD \
--with-puredb \
--with-ftpwho \
--with-quotas \
--with-altlog \
--with-tls && make && make install >> $LOG 2>&1
```

Also you can check my openssl configure command below :
```
LDFLAGS="-L$PPS_PATH/lib" CPPFLAGS="-I$PPS_PATH/include" ./config
--prefix=$PPS_PATH  \
--openssldir=$PPS_PATH/etc/openssl shared && make && make install >> $LOG 2>&1
```

**Comment by jedisct1** [comment]
Since you were able to compile it, the symbol is present in the version of openssl it was linked against.

But it's not present in the openssl version found at run-time.

Maybe you have multiple openssl installations, and it doesn't find the correct one.

That's what you get for running a frankenstein system mixing an obsolete base distribution with more recent, hand-compiled software.

**Comment by jignesh1992** [comment]
Thank you @jedisct1 for pointing me in the right direction.

Because of your help I was able to compile pure-ftpd successfully but it doesn't allow me to connect through TLS encryption. I was only able to connect through non encryption (plain FTP).

Can you help me with this? Below is the command that I used to compile pure-ftpd:-

```
LDFLAGS="-L$PPS_PATH/lib" CPPFLAGS="-I$PPS_PATH/include" ./configure --prefix=$PATH_PUREFTPD 
--with-puredb 
--with-ftpwho 
--with-quotas 
--with-altlog 
--with-tls=$PPS_PATH 
--with-certfile=/etc/ssl/private/pure-ftpd.pem 
&& make && make install >> $LOG 2>&1
```

**Comment by jignesh1992** [comment]
If anyone is facing the same issue as me, then you can resolve it by setting an 'rpath=/path/to/your/library' and then compile it.

Thank you @jedisct1 for your help. I am closing this issue.
