### ISSUE TITLE
pure-pw does not support IPv6 in IPs limits

### ISSUE THREAD

**Issue by s3rj1k** [jedisct1/pure-ftpd#89]
Because of default separator ":" in pureftpd.passwd adding IPv6 breaks parsing.

Purposing to add the ability to change separator in runtime using flag

**Comment by jedisct1** [comment]
Changing the separator would not be enough to match IPv6 subnets.

**Comment by s3rj1k** [comment]
is those fixes on ToDo list?

**Comment by jedisct1** [comment]
Not in mine, so feel free to contribute it!
