### ISSUE TITLE
IP address logging

### ISSUE THREAD

**Issue by Jakuje** [jedisct1/pure-ftpd#9]
I use version 1.0.28-3, from Debian package and IP logging doesn't work for me.

I tried writing "yes" or "1" into file /etc/pure-ftpd/conf/DontResolve, I use -H for server, but in log, I see always hostnames instead of IP addresses. It is very confusing since there are attacks with obfuscated hostname, what can't be banned like IP with Fail2Ban on my server. Do you have any idea, where can be problem?

If it is fixed in newer version, just ignore me, but I can't find similar problem for so long.

**Comment by jedisct1** [comment]
Hi,

How are you starting the server?

Do you actually see `-H` in the list of command-line switches?
