### ISSUE TITLE
TLS 1.3 not working

### ISSUE THREAD

**Issue by graxlop** [jedisct1/pure-ftpd#94]
Hello,

I have the latest pure-ftpd compiled against OpenSSL 1.1.1 and all versions of TLS work except for 1.3. I've tried with openssl s_client and the latest cURL compiled against OpenSSL 1.1.1.

Attempting a TLS 1.3 connection will result in the following error:

```
Sep 18 06:16:01 local pure-ftpd: (?@10.0.0.1) [INFO] New connection from 10.0.0.1
Sep 18 06:16:01 local pure-ftpd: (?@10.0.0.1) [ERROR] TLS renegociation
```

Here's the output from cURL attempting a file transfer:

```
curl -v 'ftp://10.0.0.1/test.bin' --user test:test --ssl-reqd -k -g -o /dev/null
*   Trying 10.0.0.1...
* TCP_NODELAY set
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0* Connected to 10.0.0.1 (10.0.0.1) port 21 (#0)
< 220---------- Welcome to Pure-FTPd [privsep] [TLS] ----------
< 220-You are user number 2 of 50 allowed.
< 220-Local time is now 06:17. Server port: 21.
< 220 You will be disconnected after 15 minutes of inactivity.
> AUTH SSL
< 500 This security scheme is not implemented
> AUTH TLS
< 234 AUTH TLS OK.
* successfully set certificate verify locations:
*   CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
} [5 bytes data]
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
} [512 bytes data]
* TLSv1.3 (IN), TLS handshake, Server hello (2):
{ [88 bytes data]
* TLSv1.3 (OUT), TLS change cipher, Client hello (1):
} [1 bytes data]
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
} [512 bytes data]
* TLSv1.3 (IN), TLS handshake, Server hello (2):
{ [155 bytes data]
* TLSv1.3 (IN), TLS handshake, [no content] (0):
{ [1 bytes data]
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
{ [6 bytes data]
* TLSv1.3 (IN), TLS handshake, [no content] (0):
{ [1 bytes data]
* TLSv1.3 (IN), TLS handshake, Certificate (11):
{ [393 bytes data]
* TLSv1.3 (IN), TLS handshake, [no content] (0):
{ [1 bytes data]
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
{ [78 bytes data]
* TLSv1.3 (IN), TLS handshake, [no content] (0):
{ [1 bytes data]
* TLSv1.3 (IN), TLS handshake, Finished (20):
{ [52 bytes data]
* TLSv1.3 (OUT), TLS handshake, [no content] (0):
} [1 bytes data]
* TLSv1.3 (OUT), TLS handshake, Finished (20):
} [52 bytes data]
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* Server certificate:
*  subject: CN=10.0.0.1
*  start date: Oct 17 18:09:56 2017 GMT
*  expire date: Oct 17 18:09:56 2018 GMT
*  issuer: CN=10.0.0.1
*  SSL certificate verify result: self signed certificate (18), continuing anyway.
} [5 bytes data]
* TLSv1.3 (OUT), TLS app data, [no content] (0):
} [1 bytes data]
> USER test
* OpenSSL SSL_read: SSL_ERROR_SYSCALL, errno 104
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
* Closing connection 0
} [5 bytes data]
* TLSv1.3 (OUT), TLS alert, [no content] (0):
} [1 bytes data]
curl: (56) OpenSSL SSL_read: SSL_ERROR_SYSCALL, errno 104
```

**Comment by maethor** [comment]
Hi.

Sadly we cannot always update to the last version of PureFTPd. A common situation when this bug can happen is Debian 9 with Sury repository. OpenSSL 1.1.1 gets installed from Sury, and PureFTPd doesn't work anymore. We are forced to disable TLS.

Is there a way to configure the TLSCipherSuite variable to explicitly tell PureFTPd to not use TLSv1.3 ciphers, to make PureFTPd v1.0.43 work again? I tried a lot of stuff but didn't find a solution. I think it would be really useful do document a workaround here.

Thanks,

**Comment by Disassembler0** [comment]
If you're using Debian or Ubuntu, it's fairly easy to recompile the packages on your own. At least that's what I did to get TLS 1.3 working on Ubuntu 18.04 with Sury repo.

1. Uncomment lines starting with `deb-src` from `/etc/apt/sources.list` for `universe` repositories and update package database with `apt-get update`
2. Install packages necessary for build with  
`apt-get build-dep pure-ftpd`
3. Download sources used by your distro maintainers (incl. patches and everything) with  
`apt-get source pure-ftpd`
4. Inside the pure-ftpd directory downloaded with the previous command, open `src/tls.c` and modify the lines as you see in 4a495c61ce22c893aed5ee57f6ce0b43c3be59ad.
5. Compile and create *.deb packages with  
`debuild`
6. Install the packages with `dpkg -i <package>`

This can be done even on a separate machine which runs the same version of the same distro and the *.deb packages then can be transferred to the *production* machine. Then you can freeze the version with `apt-mark hold <package>` to prevent it from being automatically upgraded.

I understand this solution might not be suitable for all scenarios, but maybe it'll help someone.

**Comment by maethor** [comment]
@Disassembler0 it seems a very bad security practice to hold the package of a publicly exposed service and forget it until Debian catches up. Moreover, I manage too much servers to take the risk of upgrading too frequently, that's why I am using Debian in the first place.

To me, the easier solution was to configure pinning on sury repository, and to downgrade openssl. But configuring the CipherSuite should be a better workaround.

**Comment by racke** [comment]
For your information, I uploaded new Debian packages (1.0.47-3) which have the TLS 1.3 patch applied.

**Comment by mvegetto** [comment]
Thx I grabbed this from debian sid. I can confirm this is working :).

**Comment by Railsimulatornet** [comment]
Sorry, but how can I disable TLS 1.3? I would like to use TLS 1.2 only? Unfortunately I can not find a solution on the internet.

**Comment by mpellegrin** [comment]
@Railsimulatornet 
 - Grab it from a repository that has the patched version (see previous comments)
 - Compile it yourself (see the comment of Disassembler0 for Debian or Ubuntu, I did it and it works)

Of course, it depends on your current OS and setup (you would not install a Debian package on Fedora or Arch).

Except from compiling from source, there is not way in PureFTPD, as far as I know, to disable TLS 1.3 from configuration files.

**Comment by Railsimulatornet** [comment]
Thanks

**Comment by GuillaumeSMedia** [comment]
> Thx I grabbed this from debian sid. I can confirm this is working :).

Hi, could you explain how you did this without installing a whole lot of dependencies that impact other stretch packages? Thank you :)
