### ISSUE TITLE
feat request: ssl

### ISSUE THREAD

**Issue by Ressy66** [jedisct1/pure-ftpd#95]
is there a patch to have a separate key file to cert already?
basically splitting   /etc/ssl/private/pure-ftpd.pem  into separate files, pure-ftpd.pem and pure-ftpd.key

started migrating to letsencrypt and everything works great - except pure-ftpd, we dont have employed devs or coders here so writing fancy stuff is out the question, if its not posible thats ok, we can just disable tls on pure-ftpd altogether to avoid the failures.

**Comment by jedisct1** [comment]
Hi,

You can keep the certificate and the key in separate files already. Just concatenate these files into a single `pure-ftpd.pem` file in your startup script.

**Comment by Ressy66** [comment]
thats what we've been doing and is exactly the problem we are trying to avoid, our scripting is setup for two separate files, it handles a hundreds of certs, but pureftpd is the only odd one out that breaks it when it does a restart to read the new certs on update, stopping the daemon with errors which requiring constant manual intervention which is not productive.

**Comment by jedisct1** [comment]
The manual intervention is probably always exactly the same, so you can fix your script to do it.
But really, it shoudn't take much than concatenating files.

**Comment by Ressy66** [comment]
cat'ng is what we do manually to fix, our code allows to call a hook which we call  cat, but it just wiped the cert, leaving us with only the key, if we reverse order it left cert but not key, highly annoying, I know its the fault of the developer who coded this program, but he's no longer around, thats why I ask if possible to have a --keyfile option, if not, we understand,  we use pure-ftpd  since 2004 and have no intention of moving from, so we'll just drop TLS from ftp to stop problems
