### ISSUE TITLE
Do not force TLS cert and key in one file on user

### ISSUE THREAD

**Issue by akomm** [jedisct1/pure-ftpd#97]
Why do you force the key and cert to be in a single file? This is totally incompatible with the rest of the world I have experienced so far and forced to add scripts/hooks in automation processes just to satisfy pure-ftpd with a merged copy of what is already there. This adds unnecessary layers of possible errors. Is there a reason behind this enforcement?

Beside this, very positive experience with pure-ftpd so far, thanks! :+1:

**Comment by jedisct1** [comment]
Because in 17 years that pure-ftpd has been around, you're the first person to report that concatenating files is an issue.

**Comment by akomm** [comment]
Amazing argument. In 17 years many things change and there is always someone "first".

**Comment by racke** [comment]
It might be inconvenient, but concatenating files in an automating process should be no problem.
